development:
  secret_key_base: "Use 'rake secret' to generate a secure secret key"
  sunlight_api_key: "Paste in your sunlightfoundation.com API key here"

test:
  secret_key_base: "Use 'rake secret' to generate a secure secret key"
  sunlight_api_key: FAKE_KEY

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sunlight_api_key: <%= ENV["SUNLIGHT_API_KEY"] %>
